// <auto-generated>
// Этот файл генерируется вручную, чтобы Settings.Default работал
// </auto-generated>

using System.Configuration;

namespace PyLiMan.Properties
{
	internal sealed class Settings : ApplicationSettingsBase
	{
		private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

		public static Settings Default
		{
			get { return defaultInstance; }
		}

		[UserScopedSetting()]
		[DefaultSettingValue("")]
		public string SelectedTheme
		{
			get { return ((string)this["SelectedTheme"]); }
			set { this["SelectedTheme"] = value; }
		}
	}
}